CREATE TABLE FILE_STORAGE (
    FILE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FILE_NAME NVARCHAR(256),
    FILE_TYPE NVARCHAR(100),
    FILE_SIZE INTEGER,
    FILE_CONTENT BLOB,
    UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
